/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.BibliotecaFISI;

import com.BibliotecaFISI.lib.Ejemplar;

/**
 *
 * @author Juan Aguilar
 */
public class EjemplarDetalles extends javax.swing.JFrame {
    
    private static Ejemplar ejemplar;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EjemplarDetalles.class.getName());

    /**
     * Creates new form EjemplarDetalles
     */
    public EjemplarDetalles(Ejemplar ejemplar) {
        initComponents();
        EjemplarDetalles.ejemplar = ejemplar;
        cargarDatos();
        setVisible(true);
    }

    public void cargarDatos() {
            TituloEjemplar.setText(ejemplar.titulo);
            ISBN.setText(String.valueOf(ejemplar.ISBN));
            Autor_es.setText(ejemplar.autor);
            PalabrasClaves.setText(ejemplar.palabrasClave);
            DescripcionField.setText(ejemplar.descripcion);

            // ===================== CARGAR IMAGEN PORTADA =====================
            try {
            String nombreArchivo = "portadasLibros/" + ejemplar.ISBN + ".jpg";
                java.net.URL imageURL = getClass().getClassLoader().getResource(nombreArchivo);
                if (imageURL != null) {
                    java.awt.Image img = new javax.swing.ImageIcon(imageURL).getImage();
                    java.awt.Image imgEscalada = img.getScaledInstance(imagenPortada.getWidth(), imagenPortada.getHeight(), java.awt.Image.SCALE_SMOOTH);
                    imagenPortada.setIcon(new javax.swing.ImageIcon(imgEscalada));
                    imagenPortada.setText("");  // Borra texto por defecto
                } else {
                    nombreArchivo = "portadasLibros/librodefault.jpg";
                    imageURL = getClass().getClassLoader().getResource(nombreArchivo);
                    java.awt.Image img = new javax.swing.ImageIcon(imageURL).getImage();
                    java.awt.Image imgEscalada = img.getScaledInstance(imagenPortada.getWidth(), imagenPortada.getHeight(), java.awt.Image.SCALE_SMOOTH);
                    imagenPortada.setIcon(new javax.swing.ImageIcon(imgEscalada));
                    imagenPortada.setText("");  // Borra texto por defecto
                    System.out.println("No se encontró la imagen: " + nombreArchivo);
                }
            } catch (Exception e2) {
                imagenPortada.setText("Error al cargar imagen");
                System.out.println("Error: " + e2.getMessage());
            }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        imagenPortada = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TituloEjemplar = new javax.swing.JLabel();
        Autor_es = new javax.swing.JLabel();
        PalabrasClaves = new javax.swing.JLabel();
        ISBN = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescripcionField = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel2.setBackground(new java.awt.Color(98, 21, 24));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 60));

        jLabel1.setBackground(new java.awt.Color(245, 245, 245));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 245, 245));
        jLabel1.setText("BibliotecaFISI");

        jButton1.setBackground(new java.awt.Color(98, 21, 24));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(245, 245, 245));
        jButton1.setText("Solicitar préstamo");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 433, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        imagenPortada.setText("jLabel5");
        imagenPortada.setPreferredSize(new java.awt.Dimension(275, 400));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Titulo:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Autor(es):");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Palabras claves:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("ISBN:");

        TituloEjemplar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TituloEjemplar.setText("a");
        TituloEjemplar.setMaximumSize(new java.awt.Dimension(7, 7));
        TituloEjemplar.setMinimumSize(new java.awt.Dimension(7, 40));
        TituloEjemplar.setPreferredSize(new java.awt.Dimension(7, 400));

        Autor_es.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Autor_es.setText("a");
        Autor_es.setMaximumSize(new java.awt.Dimension(400, 20));
        Autor_es.setMinimumSize(new java.awt.Dimension(400, 20));
        Autor_es.setPreferredSize(new java.awt.Dimension(400, 20));

        PalabrasClaves.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PalabrasClaves.setText("a");

        ISBN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ISBN.setText("a");

        Descripcion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Descripcion.setText("Descripción:");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(150, 250));

        DescripcionField.setEditable(false);
        DescripcionField.setBackground(new java.awt.Color(253, 253, 253));
        DescripcionField.setColumns(20);
        DescripcionField.setForeground(new java.awt.Color(70, 73, 75));
        DescripcionField.setLineWrap(true);
        DescripcionField.setRows(5);
        DescripcionField.setText("Descripción");
        DescripcionField.setWrapStyleWord(true);
        DescripcionField.setFocusable(false);
        DescripcionField.setPreferredSize(new java.awt.Dimension(150, 250));
        jScrollPane1.setViewportView(DescripcionField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(imagenPortada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TituloEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Autor_es, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PalabrasClaves, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TituloEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Autor_es, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PalabrasClaves, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imagenPortada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
      @param args the command line arguments
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Autor_es;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JTextArea DescripcionField;
    private javax.swing.JLabel ISBN;
    private javax.swing.JLabel PalabrasClaves;
    private javax.swing.JLabel TituloEjemplar;
    private javax.swing.JLabel imagenPortada;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
